### ISSUE TITLE
recent gene and variation endpoint returns 500 status code and spec error

### ISSUE THREAD

**Issue by sibyl229** [WormBase/names#257]
I get the following from `/api/recent/gene` and `/api/recent/variation`

Not sure if I'm calling the right endpoints. Please let me know if that's the issue.

```
{"spec":"(spec-tools.core/spec {:spec (clojure.spec.alpha/keys :req-un [:spec$32007/activities]), :type :map, :leaf? false})","problems":[{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-03T14:19:38.331Z","t":"2019-09-03T14:19:38Z","provenance/what":"new-gene","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":true},{"attr":"species","value":"Caenorhabditis elegans","added":true},{"attr":"id","value":"WBGene00304808","added":true},{"attr":"cgc-name","value":"test-2","added":true}],"gene/id":"WBGene00304808"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",0]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",0,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",0,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-07T14:48:53.549Z","t":"2019-09-07T14:48:54Z","provenance/what":"new-gene","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":true},{"attr":"species","value":"Caenorhabditis elegans","added":true},{"attr":"id","value":"WBGene00304809","added":true},{"attr":"cgc-name","value":"aaa-200","added":true}],"gene/id":"WBGene00304809"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",1]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",1,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",1,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-07T14:50:50.608Z","t":"2019-09-07T14:50:50Z","provenance/what":"update-gene","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"cgc-name","value":"aaa-201","added":true},{"attr":"cgc-name","value":"aaa-200","added":false}],"gene/id":"WBGene00304809"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",2]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",2,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",2,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T11:40:22.85Z","t":"2019-09-30T11:40:23Z","provenance/what":"split-gene","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"splits","value":"WBGene00304815","added":true}],"gene/id":"WBGene00000263"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",3]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",3,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",3,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T11:40:22.85Z","t":"2019-09-30T11:40:23Z","provenance/what":"split-gene","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"status","value":"live","added":true},{"attr":"splits","value":"WBGene00000263","added":true},{"attr":"species","value":"Caenorhabditis elegans","added":true},{"attr":"sequence-name","value":"CCCC.1","added":true},{"attr":"id","value":"WBGene00304815","added":true},{"attr":"biotype","value":"cds","added":true}],"gene/id":"WBGene00304815"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",4]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",4,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",4,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T12:06:40.91Z","provenance/why":"Matt testing kill bug (identifier format)","t":"2019-09-30T12:06:40Z","provenance/what":"kill-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"dead","added":true},{"attr":"status","value":"live","added":false}],"gene/id":"WBGene00304815"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",5]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",5,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",5,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T12:06:53.896Z","provenance/why":"Restoring after test.","t":"2019-09-30T12:06:53Z","provenance/what":"resurrect-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":true},{"attr":"status","value":"dead","added":false}],"gene/id":"WBGene00304815"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",6]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",6,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",6,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T12:07:16.461Z","provenance/why":"Testing kill again","t":"2019-09-30T12:07:16Z","provenance/what":"kill-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"dead","added":true},{"attr":"status","value":"live","added":false}],"gene/id":"WBGene00304815"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",7]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",7,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",7,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T12:07:44.186Z","provenance/why":"restore #2","t":"2019-09-30T12:07:44Z","provenance/what":"resurrect-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":true},{"attr":"status","value":"dead","added":false}],"gene/id":"WBGene00304815"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",8]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",8,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",8,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T12:08:02.507Z","provenance/why":"kill test #3","t":"2019-09-30T12:08:02Z","provenance/what":"kill-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"dead","added":true},{"attr":"status","value":"live","added":false}],"gene/id":"WBGene00304815"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",9]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",9,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",9,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T12:09:39.27Z","provenance/why":"restore test 3 ","t":"2019-09-30T12:09:39Z","provenance/what":"resurrect-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":true},{"attr":"status","value":"dead","added":false}],"gene/id":"WBGene00304815"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",10]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",10,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",10,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T13:40:51.868Z","t":"2019-09-30T13:40:51Z","provenance/what":"merge-genes","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"status","value":"dead","added":true},{"attr":"status","value":"live","added":false},{"attr":"merges","value":"WBGene00000264","added":true}],"gene/id":"WBGene00000263"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",11]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",11,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",11,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T13:44:41.7Z","provenance/why":"Undoing merge","t":"2019-09-30T13:44:41Z","provenance/what":"undo-merge-genes","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"status","value":"live","added":true},{"attr":"status","value":"dead","added":false},{"attr":"merges","value":"WBGene00000264","added":false}],"gene/id":"WBGene00000263"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",12]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",12,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",12,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-30T14:13:12.389Z","t":"2019-09-30T14:13:12Z","provenance/what":"merge-genes","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"status","value":"dead","added":true},{"attr":"status","value":"live","added":false},{"attr":"merges","value":"WBGene00000264","added":true}],"gene/id":"WBGene00000263"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",13]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",13,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",13,"provenance/who"]}],"type":"compojure.api.exception/response-validation","coercion":"spec","value":{"from":"2019-08-30T19:07:38Z","until":"2019-10-29T19:07:38Z","activities":[{"provenance/when":"2019-09-03T14:19:38.331Z","t":"2019-09-03T14:19:38Z","provenance/what":"new-gene","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"cgc-name","value":"test-2","added":true},{"attr":"id","value":"WBGene00304808","added":true},{"attr":"species","value":"Caenorhabditis elegans","added":true},{"attr":"status","value":"live","added":true}],"gene/id":"WBGene00304808"},{"provenance/when":"2019-09-07T14:48:53.549Z","t":"2019-09-07T14:48:54Z","provenance/what":"new-gene","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"cgc-name","value":"aaa-200","added":true},{"attr":"id","value":"WBGene00304809","added":true},{"attr":"species","value":"Caenorhabditis elegans","added":true},{"attr":"status","value":"live","added":true}],"gene/id":"WBGene00304809"},{"provenance/when":"2019-09-07T14:50:50.608Z","t":"2019-09-07T14:50:50Z","provenance/what":"update-gene","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"cgc-name","value":"aaa-200","added":false},{"attr":"cgc-name","value":"aaa-201","added":true}],"gene/id":"WBGene00304809"},{"provenance/when":"2019-09-30T11:40:22.85Z","t":"2019-09-30T11:40:23Z","provenance/what":"split-gene","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"splits","value":"WBGene00304815","added":true}],"gene/id":"WBGene00000263"},{"provenance/when":"2019-09-30T11:40:22.85Z","t":"2019-09-30T11:40:23Z","provenance/what":"split-gene","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"biotype","value":"cds","added":true},{"attr":"id","value":"WBGene00304815","added":true},{"attr":"sequence-name","value":"CCCC.1","added":true},{"attr":"species","value":"Caenorhabditis elegans","added":true},{"attr":"splits","value":"WBGene00000263","added":true},{"attr":"status","value":"live","added":true}],"gene/id":"WBGene00304815"},{"provenance/when":"2019-09-30T12:06:40.91Z","provenance/why":"Matt testing kill bug (identifier format)","t":"2019-09-30T12:06:40Z","provenance/what":"kill-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":false},{"attr":"status","value":"dead","added":true}],"gene/id":"WBGene00304815"},{"provenance/when":"2019-09-30T12:06:53.896Z","provenance/why":"Restoring after test.","t":"2019-09-30T12:06:53Z","provenance/what":"resurrect-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"dead","added":false},{"attr":"status","value":"live","added":true}],"gene/id":"WBGene00304815"},{"provenance/when":"2019-09-30T12:07:16.461Z","provenance/why":"Testing kill again","t":"2019-09-30T12:07:16Z","provenance/what":"kill-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":false},{"attr":"status","value":"dead","added":true}],"gene/id":"WBGene00304815"},{"provenance/when":"2019-09-30T12:07:44.186Z","provenance/why":"restore #2","t":"2019-09-30T12:07:44Z","provenance/what":"resurrect-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"dead","added":false},{"attr":"status","value":"live","added":true}],"gene/id":"WBGene00304815"},{"provenance/when":"2019-09-30T12:08:02.507Z","provenance/why":"kill test #3","t":"2019-09-30T12:08:02Z","provenance/what":"kill-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":false},{"attr":"status","value":"dead","added":true}],"gene/id":"WBGene00304815"},{"provenance/when":"2019-09-30T12:09:39.27Z","provenance/why":"restore test 3 ","t":"2019-09-30T12:09:39Z","provenance/what":"resurrect-gene","provenance/who":{"person/name":"Matthew Russell","person/email":"matthew.russell@wormbase.org","person/id":"WBPerson33035"},"provenance/how":"web","changes":[{"attr":"status","value":"dead","added":false},{"attr":"status","value":"live","added":true}],"gene/id":"WBGene00304815"},{"provenance/when":"2019-09-30T13:40:51.868Z","t":"2019-09-30T13:40:51Z","provenance/what":"merge-genes","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"merges","value":"WBGene00000264","added":true},{"attr":"status","value":"live","added":false},{"attr":"status","value":"dead","added":true}],"gene/id":"WBGene00000263"},{"provenance/when":"2019-09-30T13:44:41.7Z","provenance/why":"Undoing merge","t":"2019-09-30T13:44:41Z","provenance/what":"undo-merge-genes","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"merges","value":"WBGene00000264","added":false},{"attr":"status","value":"dead","added":false},{"attr":"status","value":"live","added":true}],"gene/id":"WBGene00000263"},{"provenance/when":"2019-09-30T14:13:12.389Z","t":"2019-09-30T14:13:12Z","provenance/what":"merge-genes","provenance/who":{"person/name":"Gareth W Williams","person/email":"gary.williams@wormbase.org","person/id":"WBPerson4025"},"provenance/how":"console","changes":[{"attr":"merges","value":"WBGene00000264","added":true},{"attr":"status","value":"live","added":false},{"attr":"status","value":"dead","added":true}],"gene/id":"WBGene00000263"}]},"in":["response","body"]}
```

```
{"spec":"(spec-tools.core/spec {:spec (clojure.spec.alpha/keys :req-un [:spec$32007/activities]), :type :map, :leaf? false})","problems":[{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-05T15:05:09.786Z","provenance/why":"Allele form","t":"2019-09-05T15:05:15Z","provenance/what":"new-variation","provenance/who":{"person/name":"Paul Anthony Davis","person/email":"paul.davis@wormbase.org","person/id":"WBPerson1983"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":true},{"attr":"name","value":"cas396","added":true},{"attr":"id","value":"WBVar02149605","added":true}],"variation/id":"WBVar02149605"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",0]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Paul Anthony Davis","person/email":"paul.davis@wormbase.org","person/id":"WBPerson1983"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",0,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Paul Anthony Davis","person/email":"paul.davis@wormbase.org","person/id":"WBPerson1983"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",0,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-05T16:40:48.738Z","provenance/why":"fake variation for testing","t":"2019-09-05T16:40:52Z","provenance/what":"new-variation","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":true},{"attr":"name","value":"test1","added":true},{"attr":"id","value":"WBVar02149606","added":true}],"variation/id":"WBVar02149606"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",1]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",1,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",1,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-05T16:40:57.06Z","t":"2019-09-05T16:40:57Z","provenance/what":"kill-variation","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"status","value":"dead","added":true},{"attr":"status","value":"live","added":false}],"variation/id":"WBVar02149606"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",2]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",2,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",2,"provenance/who"]},{"path":["activities","clojure.spec.alpha/nil"],"pred":"nil?","val":{"provenance/when":"2019-09-05T16:41:25.659Z","t":"2019-09-05T16:41:25Z","provenance/what":"resurrect-variation","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":true},{"attr":"status","value":"dead","added":false}],"variation/id":"WBVar02149606"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance"],"in":["activities",3]},{"path":["activities","clojure.spec.alpha/pred","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","wormbase.specs.provenance/provenance","provenance/who"],"in":["activities",3,"provenance/who"]},{"path":["activities","provenance/who"],"pred":"(clojure.core/fn [%] (clojure.core/or (clojure.core/contains? % :id) (clojure.core/contains? % :email)))","val":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"via":["spec$32007/activities","wormbase.specs.provenance/temporal-change","provenance/who"],"in":["activities",3,"provenance/who"]}],"type":"compojure.api.exception/response-validation","coercion":"spec","value":{"from":"2019-08-30T19:12:09Z","until":"2019-10-29T19:12:09Z","activities":[{"provenance/when":"2019-09-05T15:05:09.786Z","provenance/why":"Allele form","t":"2019-09-05T15:05:15Z","provenance/what":"new-variation","provenance/who":{"person/name":"Paul Anthony Davis","person/email":"paul.davis@wormbase.org","person/id":"WBPerson1983"},"provenance/how":"web","changes":[{"attr":"id","value":"WBVar02149605","added":true},{"attr":"name","value":"cas396","added":true},{"attr":"status","value":"live","added":true}],"variation/id":"WBVar02149605"},{"provenance/when":"2019-09-05T16:40:48.738Z","provenance/why":"fake variation for testing","t":"2019-09-05T16:40:52Z","provenance/what":"new-variation","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"id","value":"WBVar02149606","added":true},{"attr":"name","value":"test1","added":true},{"attr":"status","value":"live","added":true}],"variation/id":"WBVar02149606"},{"provenance/when":"2019-09-05T16:40:57.06Z","t":"2019-09-05T16:40:57Z","provenance/what":"kill-variation","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"status","value":"live","added":false},{"attr":"status","value":"dead","added":true}],"variation/id":"WBVar02149606"},{"provenance/when":"2019-09-05T16:41:25.659Z","t":"2019-09-05T16:41:25Z","provenance/what":"resurrect-variation","provenance/who":{"person/name":"Sibyl Gao","person/email":"sibyl@wormbase.org","person/id":"WBPerson26085"},"provenance/how":"web","changes":[{"attr":"status","value":"dead","added":false},{"attr":"status","value":"live","added":true}],"variation/id":"WBVar02149606"}]},"in":["response","body"]}
```

**Comment by mgrbyte** [comment]
Should be fixed in a4db331233785c52702d75e5453c4c016b6ba01e

**Comment by sibyl229** [comment]
Thanks @mgrbyte ! I'm still getting 500 error, but due to `clojure.lang.ExceptionInfo: Schema :person/email not installed!`I will test again once that's fixed.
